# Generated by Django 4.1.3 on 2022-12-04 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='FechaDeNacimiento',
        ),
    ]
