# Generated by Django 4.1.3 on 2022-12-05 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt', '0002_remove_familia_fechadenacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='FechaDeNacimiento',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 12, 5, 19, 29, 6, 25179, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
